# Generated by Django 2.2 on 2020-02-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M1', '0002_auto_20200212_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('Gender', models.CharField(default='', max_length=20)),
                ('email_address', models.CharField(default='', max_length=500)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Expertise', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('writer', models.CharField(default='Annonymos', max_length=100)),
                ('content', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_mail', models.CharField(default='', max_length=500)),
                ('content', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
