# Generated by Django 2.2 on 2020-02-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M1', '0003_doctor_news_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
